config/routes.rb
Rails.application.routes.draw do
  root 'imports#index'
  resources 'imports'
  resources 'contacts', only: [:index]
  resources 'list_contacts', only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
# == Schema Information
#
# Table name: contacts
#
#  id         :integer          not null, primary key
#  first_name :string
#  last_name  :string
#  email      :string
#  import_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_contacts_on_import_id  (import_id)
#
# Foreign Keys
#
#  fk_rails_a2e82c9f09  (import_id => imports.id)
#

class Contact < ApplicationRecord
  belongs_to :import

  validates :first_name, :last_name, presence: true
  validates :email, presence: true
  validates :email, uniqueness: true
  validates_format_of :email,:with => /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :first_name, :last_name, length: { minimum: 3 }
  validate :full_name_uniqueness

  def full_name
    "#{first_name} #{last_name}"
  end
  
  def full_name_uniqueness
    if Contact.exists?(first_name: first_name, last_name: last_name)
     errors.add :base, "#{full_name} already exists"
    end
  end
end

app/models/import.rb
# == Schema Information
#
# Table name: imports
#
#  id         :integer          not null, primary key
#  name       :string
#  attachment :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Import < ApplicationRecord
  has_many :contacts, dependent: :destroy
  has_many :list_contacts, dependent: :destroy
  mount_uploader :attachment, AttachmentUploader
end

app/models/list_contact.rb
# == Schema Information
#
# Table name: list_contacts
#
#  id         :integer          not null, primary key
#  first_name :string
#  last_name  :string
#  email      :string
#  reason     :string
#  validated  :boolean          default(FALSE)
#  import_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_list_contacts_on_import_id  (import_id)
#
# Foreign Keys
#
#  fk_rails_306093da3e  (import_id => imports.id)
#

class ListContact < ApplicationRecord
  belongs_to :import
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  end
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController

  def index
    @imports = Import.all

    @contacts = Contact.all
    @invalid_contacts = ListContact.where(validated: false)
  end

  def new
    @import = Import.new
  end

  def create
    @import = Import.new(import_params)
    if @import.save
      XlsxParser.new(@import).call

      redirect_to imports_path, notice: "The import #{@import.name} has been uploaded."
    else
      flash[:error]="#{@import.name} has not been imported"
    end
  end

  def show
    @import = Import.find(params[:id])
  end

  private

  def import_params
    params.require(:import).permit(:name, :attachment)
  end
end

app/controllers/list_contacts_controller.rb
class ListContactsController < ApplicationController
  def index
    @contacts = ListContact.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/index.haml
%h1
  Contacts list

app/views/imports/index.haml
%h1
  Contacts list 
  =link_to "New Import", new_import_path, class: "btn btn-primary"

%h2
  Valid contacts

%div
  %table.table.table-bordered.table-striped
    %thead
      %tr
        %th
          First name
        %th
          Last name
        %th
          Email

    %tbody
    -unless @contacts.empty?
      -@contacts.each do |contact|
        %tr
          %td
            =contact.first_name
          %td  
            =contact.last_name 
          %td  
            =contact.email

%h2
  Invalid contacts
  
%div
  %table.table.table-bordered.table-striped
    %thead
      %tr
        %th
          First name
        %th
          Last name
        %th
          Email
        %th
          Reason

    %tbody
      -@invalid_contacts.each do |contact|
        %tr
          %td
            =contact.first_name
          %td  
            =contact.last_name 
          %td  
            =contact.email
          %td  
            =contact.reason 

app/views/imports/new.haml
= simple_form_for @import do |f|
  = f.input :attachment, as: :file
  = f.submit "Import File", class: "btn btn-primary"

app/views/layouts/application.haml
!!!
%html
  %head
    %title
    =csrf_meta_tags

    =stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload'
    =javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href="#") xlsxImport
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li= link_to "Home", root_path
            %li= link_to "Contacts list", list_contacts_path

    .container
      -if !flash[:notice].blank?
        .alert.alert-info
          =flash[:notice]
        
      =yield

app/views/list_contacts/index.haml
%h1
  Contacts

%div
  %table.table.table-bordered.table-striped
    %thead
      %tr
        %th
          First name
        %th
          Last name
        %th
          Email
        %th
          Reason

    %tbody
      -@contacts.each do |contact|
        %tr
          %td
            =contact.first_name
          %td  
            =contact.last_name 
          %td  
            =contact.email
          %td  
            =contact.reason 